# fonts
PRODUCT_COPY_FILES += \
    vendor/ancient/prebuilt/common/fonts/Abel-Regular.ttf:system/fonts/Abel-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/AdamCGPro-Regular.ttf:system/fonts/AdamCGPro-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/AdventPro-Regular.ttf:system/fonts/AdventPro-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/AlexanaNeue-Regular.ttf:system/fonts/AlexanaNeue-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/AlienLeague-Regular.ttf:system/fonts/AlienLeague-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/ArchivoNarrow-Regular.ttf:system/fonts/ArchivoNarrow-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/AutourOne-Regular.ttf:system/fonts/AutourOne-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Azedo-Light.ttf:system/fonts/Azedo-Light.ttf \
    vendor/ancient/prebuilt/common/fonts/BadScript-Regular.ttf:system/fonts/BadScript-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/BigNoodleTilting-Regular.ttf:system/fonts/BigNoodleTilting-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Biko-Regular.ttf:system/fonts/Biko-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Blern-Regular.ttf:system/fonts/Blern-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/CherrySwash-Regular.ttf:system/fonts/CherrySwash-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Cocon-Regular.ttf:system/fonts/Cocon-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Codystar.ttf:system/fonts/Codystar.ttf \
    vendor/ancient/prebuilt/common/fonts/Fester-Medium.ttf:system/fonts/Fester-Medium.ttf \
    vendor/ancient/prebuilt/common/fonts/FoxAndCat-Regular.ttf:system/fonts/FoxAndCat-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/GinoraSans-Regular.ttf:system/fonts/GinoraSans-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Gobold.ttf:system/fonts/Gobold.ttf \
    vendor/ancient/prebuilt/common/fonts/IBMPlexMono.ttf:system/fonts/IBMPlexMono.ttf \
    vendor/ancient/prebuilt/common/fonts/Inkferno-Regular.ttf:system/fonts/Inkferno-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Instruction-Regular.ttf:system/fonts/Instruction-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/JackLane-Regular.ttf:system/fonts/JackLane-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Jura-Regular.ttf:system/fonts/Jura-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/KellySlab-Regular.ttf:system/fonts/KellySlab-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Metropolis1920-Regular.ttf:system/fonts/Metropolis1920-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Monad-Regular.ttf:system/fonts/Monad-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Neoneon-Regular.ttf:system/fonts/Neoneon-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Noir-Regular.ttf:system/fonts/Noir-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/North-Regular.ttf:system/fonts/North-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/OutrunFuture-Regular.ttf:system/fonts/OutrunFuture-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Pompiere-Regular.ttf:system/fonts/Pompiere-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Qontra-Regular.ttf:system/fonts/Qontra-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Raleway-Light.ttf:system/fonts/Raleway-Light.ttf \
    vendor/ancient/prebuilt/common/fonts/ReemKufi-Regular.ttf:system/fonts/ReemKufi-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Riviera-Regular.ttf:system/fonts/Riviera-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/RoadRage-Regular.ttf:system/fonts/RoadRage-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Satisfy-Regular.ttf:system/fonts/Satisfy-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/SeaweedScript-Regular.ttf:system/fonts/SeaweedScript-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/SedgwickAveDisplay-Regular.ttf:system/fonts/SedgwickAveDisplay-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Snowstorm-Regular.ttf:system/fonts/Snowstorm-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/ThemeableClock-vcrosd.ttf:system/fonts/ThemeableClock-vcrosd.ttf \
    vendor/ancient/prebuilt/common/fonts/TheOutbox-Regular.ttf:system/fonts/TheOutbox-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Union-Regular.ttf:system/fonts/Union-Regular.ttf \
    vendor/ancient/prebuilt/common/fonts/Vibur.ttf:system/fonts/Vibur.ttf \
    vendor/ancient/prebuilt/common/fonts/Voltaire.ttf:system/fonts/Voltaire.ttf
